#!/bin/env python

from __future__ import print_function

import sys, os

def install_path(path):
    with open(path) as f:
        l = f.readline()
        if not l:
            return None
        i = l.find("~/")
        return l[i:].strip() if i >= 0 else None;

base_dir = os.path.dirname(sys.argv[0])
conf_dirs = [ 'default' ] + sys.argv[1:]

configs = {}

for d in conf_dirs:
    for root, dirs, files in os.walk(os.path.join(base_dir, d)):
        for f in files:
            src = os.path.join(root, f)
            dst = install_path(src)
            configs[dst] = src

for dst, src in configs.items():
    expanded_dst = os.path.expanduser(dst)
    if os.path.exists(expanded_dst):
        print('file exists, skipping: %s' % dst, file=sys.stderr)
        continue
    try:
        with open(src) as fin, open(expanded_dst, 'w') as fout:
            while True:
                line = fin.readline()
                if not line:
                    break
                fout.write(line)
    except (OSError, IOError) as e:
        print('error: %s => %s (%s)' % (src, dst, e.strerror), file=sys.stderr)
