# ~/.bashrc
#
# This file is sourced by all *interactive* bash shells on startup,
# including some apparently interactive shells such as scp and rcp
# that can't tolerate any output.  So make sure this doesn't display
# anything or bad things will happen !


# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

if [[ $- != *i* ]]; then
	# Shell is non-interactive.  Be done now!
	return
fi


# Put your fun stuff here.

if [ -r '/usr/share/git/git-prompt.sh' ]; then
	source '/usr/share/git/git-prompt.sh'
	prompt_command () {
		local ps1_start='\[\033[01;32m\]\u@\h\[\033[01;34m\] \w\[\033[00m\]'
		local ps1_end=' \$ '
		__git_ps1 "$ps1_start" "$ps1_end"
	}

	PROMPT_COMMAND='prompt_command'
	GIT_PS1_SHOWDIRTYSTATE=1
	GIT_PS1_SHOWSTASHSTATE=1
	GIT_PS1_SHOWUNTRACKEDFILES=1
	GIT_PS1_DESCRIBE_STYLE='describe'
	GIT_PS1_SHOWUPSTREAM='auto'
	GIT_PS1_SHOWCOLORHINTS=1
fi
