# ~/.bashrc
#
# This file is sourced by all *interactive* bash shells on startup,
# including some apparently interactive shells such as scp and rcp
# that can't tolerate any output.  So make sure this doesn't display
# anything or bad things will happen !


# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

if [[ $- != *i* ]]; then
	# Shell is non-interactive.  Be done now!
	return
fi


# Put your fun stuff here.

[ -z "$SSH_AUTH_SOCK" ] && eval $(ssh-agent | grep -v '^echo')

git_prompt_files="
/usr/share/git-core/contrib/completion/git-prompt.sh
/usr/share/git/git-prompt.sh
"

for git_prompt_file in $git_prompt_files; do
	[ -f $git_prompt_file ] && break
done

if [ -r $git_prompt_file ]; then
	source $git_prompt_file
	prompt_command () {
		local ps1_start='\[\033[01;32m\]\u@\h\[\033[01;34m\] \w\[\033[00m\]'
		local ps1_end=' \$ '
		__git_ps1 "$ps1_start" "$ps1_end"
	}

	PROMPT_COMMAND='prompt_command'
	unset GIT_PS1_SHOWDIRTYSTATE
	GIT_PS1_SHOWSTASHSTATE=1
	GIT_PS1_SHOWUNTRACKEDFILES=1
	GIT_PS1_DESCRIBE_STYLE='describe'
	GIT_PS1_SHOWUPSTREAM='auto'
	GIT_PS1_SHOWCOLORHINTS=1
fi

alias e="emacsclient -t -a ''"

module load docker/engine
