# ~/.xinitrc

[ -f $HOME/.Xresources ] && xrdb $HOME/.Xresources

wallpaper="$HOME/wallpaper/pillars.png"

feh --bg-fill "$wallpaper"
xautolock -time 5 -locker "i3lock -i '$wallpaper' -e -d" &

exec i3
#exec fvwm
#exec xmonad
